spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/enigma_homol}
spring.datasource.username=${DB_USER:enigma}
spring.datasource.password=${DB_PASSWORD:enigma_homol}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
